**Activation Functions**

In [44]:
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [45]:
sigmoid(100)

1.0

In [46]:
sigmoid(1)

0.7310585786300049

In [47]:
sigmoid(-57)

1.7587922024243116e-25

In [48]:
def tanh(x):
  return (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))

In [49]:
tanh(-57)

-1.0

In [50]:
tanh(150)

1.0

In [51]:
tanh(1)

0.7615941559557649

In [52]:
def relu(x):
  return max(0, x)

In [53]:
relu(2)

2

In [54]:
relu(-4)

0

In [55]:
relu(1)

1

In [56]:
def leaky_relu(x):
  return max(0.1*x, x)

In [57]:
leaky_relu(-100)

-10.0

In [58]:
leaky_relu(5)

5

**Matrix**

In [59]:
import numpy as np

In [60]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [61]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [62]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [63]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [64]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

**Loss or cost Functions**

In [65]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

**Mean Absolute Error**

In [66]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [67]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

**Implement same thing using numpy**

In [68]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [69]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [70]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [71]:
mae_np(y_predicted, y_true)

0.5

**Log Loss or Binary Cross Entropy**

In [72]:
np.log([0])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [73]:
epsilon = 1e-15

In [74]:
np.log([1e-15])

array([-34.53877639])

In [75]:
y_predicted

array([1, 1, 0, 0, 1])

In [76]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [77]:
1-epsilon

0.999999999999999

In [78]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [79]:
y_predicted_new = np.array(y_predicted_new)

In [80]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [81]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [82]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [83]:
log_loss(y_true, y_predicted)

17.2696280766844

**Mean Squared Error (or MSE)**

In [84]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [85]:
mse(y_true, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

**By using numpy**

In [86]:
np.mean(np.square(y_true-y_predicted))

0.366